log:
  path: ${LOG_PATH:/data/logs/secret-config}

spring:
  application:
    name: secret-config
  data:
    redis:
      database: 0

server:
  port: 9527
  servlet:
    context-path: /secret-config